version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 9004:9003
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      XDEBUG_CONFIG: client_host=host.docker.internal
      DEBUG: 1
  composer:
    image: composer
  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: localtest
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
